[custom]
  
ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/rnylx/Script/main/rule/Direct.yaml
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list

ruleset=✈️,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=✈️,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=✈️,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list

ruleset=🛑 BanAd,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml

ruleset=🌰,clash-classic:https://raw.githubusercontent.com/rnylx/Script/main/rule/Spical.yaml
;ruleset=👹,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml

ruleset=🪙,clash-classic:https://raw.githubusercontent.com/rnylx/Script/main/rule/OneD.yaml

ruleset=Ⓜ️ Xbox,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
ruleset=Ⓜ️ Xbox,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Xbox/Xbox.yaml
ruleset=🎮 STEAM,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
ruleset=🎮 Games,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml

ruleset=🍎 Apple,[]DOMAIN-SUFFIX,apple.com
ruleset=🍎 Apple,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml

ruleset=🤖,https://raw.githubusercontent.com/cutethotw/ClashRule/main/Rule/ChatGPT.list
ruleset=🤖,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
;ruleset=🤖,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
;ruleset=🤖,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml
;ruleset=🤖,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml

ruleset=🇹🇼 TW ,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml

ruleset=🌏 Global,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml
ruleset=🌏 Global,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml

;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=DIRECT,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMedia/ChinaMedia.yaml
;ruleset=DIRECT,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/China/China_Classical.yaml
;ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaNoMedia/ChinaNoMedia_Classical.yaml

;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
;ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/rnylx/Script/refs/heads/main/rule/D.yaml
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=DIRECT,[]GEOIP,CN
ruleset=🐟 Final,[]FINAL

custom_proxy_group=✈️`select`[]🐇`[]🚀`[]🌰`[]🪙`[]👹`[]DIRECT
custom_proxy_group=🐇`select`.*0.2.*
custom_proxy_group=🚀`select`.*
custom_proxy_group=🌰`select`.*V2ray.*`.*GL.*`[]DIRECT
custom_proxy_group=🪙`select`.*
custom_proxy_group=🤖`select`[]✈️`.*美国.*
custom_proxy_group=👹`select`.*特殊.*

custom_proxy_group=🎮 STEAM`select`[]🌰`[]🐇`[]🚀`[]👹`[]DIRECT
custom_proxy_group=🎮 Games`select`[]🌰`[]🐇`[]🚀`[]👹`[]DIRECT`[]🎮 STEAM
custom_proxy_group=Ⓜ️ Xbox`select`[]🌰`[]🐇`[]🚀`[]👹`[]DIRECT`[]🎮 STEAM

custom_proxy_group=🍎 Apple`select`[]✈️`[]DIRECT

custom_proxy_group=🌏 Global`select`[]✈️`[]DIRECT
custom_proxy_group=🐟 Final`select`[]✈️`[]DIRECT
custom_proxy_group=🛑 BanAd`select`[]REJECT`[]DIRECT`[]✈️

custom_proxy_group=🇭🇰 HK`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 JP`url-test`(日本|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 US`url-test`(美)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 TW`url-test`(台|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 SG`url-test`(新加坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 KR`url-test`(KR|Korea|KOR|韩)`http://www.gstatic.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true
